name: Lint sh

on:
  push:
    branches: [main]
    paths: ['scripts/install_plugin.sh']
  pull_request:
    branches: [main]
    paths: ['scripts/install_plugin.sh']

jobs:
  lint-sh:
    name: Lint scripts/install_plugin.sh
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v4
      - uses: luizm/action-sh-checker@v0.9.0
        with:
          sh_checker_checkbashisms_enable: true
